# An analysis of African countries by GDP (2024 Estimates)

# 1. Introduction
## GDP is defined as the "total monetary or market value of all the finished 
## goods and services produced within a country’s borders in a specific time period"

# (A) Load the required libraries

library(tidyverse)
library(rvest)
library(stringr)
library(janitor)
library(gghighlight)
library(readr)
library(treemapify)
library(scales)
library(ggrepel)

#### PRELOAD DATA FROM THE PROCESSED DATASETS FILE ####

# # (C) Get the data from Wikipedia
# 
# link <- "https://en.wikipedia.org/wiki/List_of_African_countries_by_GDP_(nominal)"
# africa_country <- link %>%
#   read_html("[class='wikitable sortable']") %>% 
#   html_table(fill = TRUE)
# 
# africa_country_GDP <- africa_country[[1]]
# 
# # (D) Clean the data, fix columns and county labels
# 
# africa_country_GDP_clean <- africa_country_GDP %>%
#   clean_names() %>%
#   filter(country != "Total") %>%
#   rename("nominal_gdp" = "nominal_gdp_billion_us_1",
#          "gdp_per_capita" = "per_capita_us_1") %>%
#   mutate(across(everything(), ~ str_remove_all(., "\\[6\\]|\\(2019\\)")))
# 
# # parsing out the number is very critical as a simple conversion using 
# # as._____() will not work
# 
# str(africa_country_GDP_clean)
# 
# africa_country_GDP_clean$nominal_gdp <- parse_number(africa_country_GDP_clean$nominal_gdp)
# africa_country_GDP_clean$gdp_per_capita <- parse_number(africa_country_GDP_clean$gdp_per_capita)
# 
# # Nominal GDP table
# 
# africa_country_GDP_clean_1 <- subset(africa_country_GDP_clean, select = -gdp_per_capita)
# str(africa_country_GDP_clean_1)
# 
# # Per capita table 
# 
# africa_country_GDP_clean_2 <- subset(africa_country_GDP_clean, select = -nominal_gdp)
# str(africa_country_GDP_clean_1)
# 
# # Save the processed dataset
# 
# write.csv(africa_country_GDP_clean_1, "sub_pro_5_africa_economy_wiki/processed_datasets/nominal_gdp")
# write.csv(africa_country_GDP_clean_2, "sub_pro_5_africa_economy_wiki/processed_datasets/gdp_per_capita")

# Load the data

africa_country_GDP_clean_1 <- read_csv("sub_pro_5_africa_economy_wiki/processed_datasets/nominal_gdp")
africa_country_GDP_clean_2 <- read_csv("sub_pro_5_africa_economy_wiki/processed_datasets/gdp_per_capita")

# (E) Plots

## 1) A bar plot demonstrating the GDP of the top 5 economies relative to the rest of the continent

ggplot(africa_country_GDP_clean_1, aes(reorder(country, +nominal_gdp), nominal_gdp, fill = country)) +
  geom_bar(stat = "identity") + coord_flip() +
  gghighlight(max(nominal_gdp) > 200) + 
  scale_fill_brewer(palette="GnBu") +
  labs(x = "Country",
       y = "GDP (billions of US$)",
       title = "Majority of Africa's nominal GDP in 2024\nwas generated by 5 countries",
       subtitle = "",
       caption = "Data Source: Wikipedia") +
  theme_classic() +
  scale_y_continuous(labels = comma,
                     breaks = seq(0, 450, by = 100),
                     minor_breaks = seq(0, 450, by = 10)) +
  theme(axis.title.x =element_text(size = 25),
        axis.title.y =element_text(size = 25),
        axis.text.x = element_text(size = 25),
        axis.text.y = element_text(size = 15),
        axis.ticks.length.x = unit(0.2, "cm"),  # Lengthen the ticks
        axis.ticks.minor.x = element_line(color = "black", size = 2),  # Show minor ticks
        plot.title = element_text(family="Helvetica", face="bold", size = 35, hjust = 0.5, vjust=0),
        plot.subtitle = element_text(family="Helvetica", face="bold", size = 25),
        plot.caption = element_text(family = "Helvetica",size = 25, face = "bold", hjust = -0.75, vjust = 1),
        plot.background = element_rect(fill = "bisque1", colour = "bisque1"),
        panel.background = element_rect(fill = "bisque1", colour = "bisque1"),
        plot.title.position = 'plot',
        legend.title = element_blank(),
        legend.position = "none") 

ggsave("sub_pro_5_africa_economy_wiki/images/bar_top_5_africa_gdp_2024.png", width = 12, height = 12, dpi = 300)

## 2) A tree map demonstrating the GDP of the top 5 economies relative to the rest of the continent

# Get the top 5 economies
africa_country_GDP_clean_top_5 <- africa_country_GDP_clean_1[1:5, ]

# Get the bottom 49
africa_country_GDP_clean_bottom <- africa_country_GDP_clean_1[6:54, ]

# Sum the bottom 49
africa_country_GDP_clean_bottom_total <- africa_country_GDP_clean_bottom %>%
  bind_rows(summarise(., across(where(is.numeric), sum),
                      across(where(is.character), ~'Rest of the Continent'))) %>%
  filter(row_number() %in% 50)

# Combine the top 5 economies with the combined GDP of the other 49 countries
africa_country_GDP_clean_top_5_bottom_total <- rbind(africa_country_GDP_clean_top_5, 
                                                     africa_country_GDP_clean_bottom_total)

# Create new columns to provide labels for the treemap
africa_country_GDP_clean_top_5_bottom_total_new_col <- africa_country_GDP_clean_top_5_bottom_total %>%
  mutate(nominal_gdp_new_1 = paste("$", nominal_gdp, sep = "")) %>%
  mutate(nominal_gdp_new_2 = paste(nominal_gdp_new_1, "Billion", sep = " ")) 

# Plot the tree map
ggplot(africa_country_GDP_clean_top_5_bottom_total_new_col, 
       aes(area = nominal_gdp, fill = country, 
           label = paste(country, nominal_gdp_new_2, sep = "\n"))) +
  geom_treemap() +
  labs(title = "Over half of Africa's nominal GDP is\ngenerated by 5 countries (2024)",
       subtitle = "",
       fill = "",
       caption = "Data Source: Wikipedia") +
  geom_treemap_text(colour = "black",
                    place = "centre",
                    size = 25,
                    grow = FALSE) + 
  theme(legend.position = "none",
        plot.title = element_text(size=40, hjust = 0.5, vjust = 1, face="bold"),
        plot.subtitle = element_text(size=15, hjust = 0.5, vjust = 1),
        legend.text = element_text(size = 20),
        plot.caption = element_text(size = 25, hjust = 0, vjust = 1, face = "bold"),
        panel.background = element_rect(fill="bisque1"),
        plot.background = element_rect(fill="bisque1"),
        legend.background = element_rect(fill="bisque1")) +
  scale_fill_brewer(palette = "GnBu")

ggsave("sub_pro_5_africa_economy_wiki/images/treemap_top_5_africa_gdp_2024.png", width = 12, height = 12, dpi = 300)

## 3) A bar plot to compare the GDP per capita of African countries

ggplot(africa_country_GDP_clean_2, aes(reorder(country, +gdp_per_capita), gdp_per_capita, fill = country)) +
  geom_bar(stat = "identity") + coord_flip() +
  gghighlight(max(gdp_per_capita) > 10000) + 
  geom_hline(yintercept = 2000, linetype = "dashed") +
  annotate("text", x=15, y=2500, label="GDP per capita = $2000", size = 8, angle=90) +
  geom_hline(yintercept = 10000, linetype = "dashed") +
  annotate("text", x=15, y=10500, label="GDP per capita = $10000", size = 8, angle=90) +
  scale_fill_brewer(palette="BuGn") +
  labs(x = "Country",
       y = "GDP per capita (US$)",
       title = "Only 2 countries in Africa were part of\nthe $10k or greater club",
       subtitle = "",
       caption = "Data Source: Wikipedia") +
  theme_classic() +
  scale_y_continuous(labels = comma, 
                     breaks = seq(0, 25000, by = 5000),
                     minor_breaks = seq(0, 25000, by = 1000)) +
  theme(axis.title.x =element_text(size = 25),
        axis.title.y =element_text(size = 25),
        axis.text.x = element_text(size = 25),
        axis.text.y = element_text(size = 15),
        axis.ticks.minor = element_line(color = "black", size = 5),
        plot.title = element_text(family="Helvetica", face="bold", size = 35, hjust = 0.5, vjust=0.5),
        plot.subtitle = element_text(family="Helvetica", size = 25, hjust = 0.5, vjust=0.5),
        plot.caption = element_text(family = "Helvetica",size = 25, face = "bold", hjust = -0.75, vjust = 1),
        plot.background = element_rect(fill = "bisque1", colour = "bisque1"),
        panel.background = element_rect(fill = "bisque1", colour = "bisque1"),
        plot.title.position = 'plot',
        legend.title = element_blank(),
        legend.position = "none") 

ggsave("sub_pro_5_africa_economy_wiki/images/bar_top_2_africa_gdp_per_cap_2024.png", width = 12, height = 12, dpi = 300)

## 4) Scatter plot to compare GDP per capita, population size, and nominal GDP

# # Import the required data from Wikipedia
# 
# link_pop <- "https://en.wikipedia.org/wiki/List_of_African_countries_by_population"
# africa_country_pop <- link_pop %>%
#   read_html("[class='wikitable sortable']") %>% 
#   html_table(fill = TRUE)
# 
# africa_country_pop_1 <- africa_country_pop[[1]]
# 
# # Clean the data, fix columns and county labels
# 
# africa_country_pop_1_clean <- africa_country_pop_1 %>%
#   clean_names() %>%
#   select(c(country, africapopulation_4)) %>%
#   filter(country != "Total") %>%
#   rename("population" = "africapopulation_4")
# 
# # parsing out the number is very critical as a simple conversion using 
# # as._____() will not work
# 
# str(africa_country_pop_1_clean)
# 
# africa_country_pop_1_clean$population <- parse_number(africa_country_pop_1_clean$population)
# 
# str(africa_country_pop_1_clean)
# 
# africa_country_pop_1_clean[africa_country_pop_1_clean=="DR Congo"] <- "Democratic Republic of the Congo"
# africa_country_pop_1_clean[africa_country_pop_1_clean=="Congo"] <- "Republic of Congo"
# africa_country_pop_1_clean[africa_country_pop_1_clean=="Gambia"] <- "The Gambia"
# 
# # Join the tables 
# 
# africa_country_GDP_pop <- left_join(africa_country_GDP_clean, africa_country_pop_1_clean, by = "country")
# 
# # Save the processed dataset
# 
# write.csv(africa_country_GDP_pop, "sub_pro_5_africa_economy_wiki/processed_datasets/gdp_population")

# Load the data

africa_country_GDP_pop <- read_csv("sub_pro_5_africa_economy_wiki/processed_datasets/gdp_population")

# Basic bubble plot / ####### Not very useful #########

ggplot(africa_country_GDP_pop, aes(x=gdp_per_capita, y=nominal_gdp)) +
  geom_point(alpha=0.5, size = 4, color = "darkblue") + 
  geom_rect(aes(xmin = 0, xmax = 5000, ymin = 0, ymax = 100), 
            alpha = 0, size = 1, color = "black") +
  geom_text_repel(aes(label = ifelse(gdp_per_capita >= 5000 | nominal_gdp >= 100, country, "")), 
                  size = 7.5, max.overlaps = 20, seed = 42, segment.length = 2, segment.size = 1) +
  labs(x = "GDP per capita (US$)",
       y = "Nominal GDP (Billions, US$)",
       title = "Most African countries have a nominal GDP below\nUS$ 100 billion and GDP per capita below US$ 5000",
       subtitle = "",
       caption = "Data Source: Wikipedia") +
  theme_classic() +
  scale_y_continuous(labels = comma, 
                     breaks = seq(0, 500, by = 100),
                     minor_breaks = seq(0, 500, by = 50)) +
  theme(axis.title.x =element_text(size = 25),
        axis.title.y =element_text(size = 25),
        axis.text.x = element_text(size = 25),
        axis.text.y = element_text(size = 25),
        plot.title = element_text(family="Helvetica", face="bold", size = 35, hjust = 0.5, vjust=0.5),
        plot.subtitle = element_text(family="Helvetica", size = 25, hjust = 0.5, vjust=0.5),
        plot.caption = element_text(family = "Helvetica",size = 25, face = "bold", hjust = 0, vjust = 1),
        plot.background = element_rect(fill = "bisque1", colour = "bisque1"),
        panel.background = element_rect(fill = "bisque1", colour = "bisque1"),
        plot.title.position = 'plot',
        legend.title = element_blank(),
        legend.position = "none") 

ggsave("sub_pro_5_africa_economy_wiki/images/scatter_gdp_vs_gdp_per_cap_2024.png", width = 12, height = 12, dpi = 300)
